services:
  prom-stream-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    hostname: prom-stream-gateway
    ports:
      - '9091:8080'
    networks: ["default-network"]
  redis:
      image: redis:latest
      container_name: redis
      restart: always
      hostname: redis
      ports:
        - '6379:6379'
      networks: ["default-network"]
      command: ["redis-server", "--save", "", "--appendonly", "no"]
networks:
  default-network:
    driver: bridge