services:
  prom-stream-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    hostname: prom-stream-gateway
    environment:
      - Redis__ConnectionString=redis:6379
      - Redis__MetricQueueWorkers=4
      - Redis__MetricQueueDatabase=0
      - Redis__MetricQueueKey=prom-stream-gateway:metric-queue
      - Metrics__SortIncomingLabels=true
    networks:
      - gateway
    ports:
      - '9091:8080'
  redis:
      image: redis:latest
      container_name: redis
      restart: always
      hostname: redis
      ports:
        - '6379:6379'
      networks:
        - gateway
      command: ["redis-server", "--save", "", "--appendonly", "no"]
networks:
  gateway:
    name: prom-stream-gateway
    driver: bridge